services:
  site:
    web:
      build: ./frontend
      network_mode: "host"
      depends_on:
        - server

  server:
    build: ./backend
    network_mode: "host"
    depends_on:
      - db
  
  db:
    image: "mongodb/mongodb-community-server:latest"
    network_mode: "host"